const RecommendationData = [
    {img:"trending1.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending2.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending1.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},

    {img:"trending1.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending2.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending1.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
]
const eventDetailImage = [
    {img:"Image120.jpg"},
    {img:"Image118.jpg"},
    {img:"Image122.jpg"},
    {img:"Image121.jpg"},
    /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
]
const Treading = [
    {img:"trending1.jpg", rank:"one.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg", rank:"two.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending2.jpg", rank:"three.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"trending1.jpg", rank:"four.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    {img:"recommend2.jpg", rank:"five.svg", rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"AED 1800 per person"},
    /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
]
const SliderCardData = [
    {img:"trending1.jpg", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
    {img:"recommend2.jpg", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
    {img:"trending2.jpg", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
    {img:"trending1.jpg", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod et dolore magna aliquyam erat…"},
    {img:"recommend2.jpg", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:" 4.9 (123 reviews)", date:"Nov 10-29", title:"Men's Golf League", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod dolore magna aliquyam erat…"},
    /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
]
const RecommendationBannerData = [
  {
    Event_ID: 10005,
    Operator_ID: 20002,
    url: "./img/Product1.png",
    Operator_Name: "Dark Roast",
    Event_Category: "Golf",
    Event_Name: "Round of Golf",
    Event_Description:
      "The course will test even the most seasoned golfer due to cunning bunker design and water hazards that affect twelve of the eighteen holes...",
    Event_Start_Date: "Jan 01, 2023",
    Event_End_Date: "12/01/2022",
    Event_Start_Time: "10:30 AM | 3:00 PM | 5:30 PM",
    Event_End_Time: "11:00 PM",
    Seat_Booking_Availability: 20,
    Event_Location: "Sindalah Island",
    Event_Status: "Scheduled",
    Event_Capacity: 200,
    Overall_Event_Rating: 5.0,
    Operator_Rating: 4.9,
    vibes_text: "Overwhelmed",
    removedWhenCancel: true,
    imgurl: [
      { img: "./img/golf.jpg" },
      { img: "./img/golf.jpg" },
      { img: "golf.jpg" },
      { img: "golf.jpg" },
      { img: "golf.jpg" },
    ],
  },
  {
    Event_ID: 10012,
    Operator_ID: 20005,
    url: "./img/Product1.png",
    Operator_Name: "Basket of gold",
    Event_Category: "Tech Expo",
    Event_Name: "Tech Expo",
    Event_Description:
      "Most awaited concert featuring a spectacular line-up of Grammy-nominated musicians from across the world coming together to create some fine Tech Expo.",
    Event_Start_Date: "Dec 11, 2022",
    Event_End_Date: "Dec 11, 2022",
    Event_Rank: "one.svg",
    Event_Start_Time: "3:00 PM",
    Event_Counter_Time: 3601,
    Event_End_Time: "11:59 PM",
    Seat_Booking_Availability: 20,
    Event_Location: "Sindalah Island",
    Event_Status: "Completed",
    Event_Capacity: 300,
    Overall_Event_Rating: 4.6,
    Operator_Rating: 5,
    Client_Booked: true,
    vibes_text: "Overwhelmed",
    imgurl: [
      { img: "Jazz1.jpg" },
      { img: "Jazz2.jpg" },
      { img: "Jazz3.jpg" },
      { img: "Jazz4.jpg" },
      { img: "Jazz5.jpg" },
    ],
  },
  {
    Event_ID: 10013,
    Operator_ID: 20003,
    url: "./img/Product1.png",
    Operator_Name: "Basket of gold",
    Event_Category: "Surfing",
    Event_Name: "Surfing",
    Event_Description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut...",
    Event_Start_Date: "Dec 11, 2022",
    Event_End_Date: "Dec 11, 2022",
    Event_Rank: "two.svg",
    Event_Start_Time: "3:00 PM",
    Event_Counter_Time: 3601,
    Event_End_Time: "7:30 PM",
    Seat_Booking_Availability: 20,
    Event_Location: "Sindalah Island",
    Event_Status: "Completed",
    Event_Capacity: 100,
    Overall_Event_Rating: 4.6,
    Operator_Rating: 3,
    Client_Booked: true,
    vibes_text: "Joyed",
  },
  {
    Event_ID: 10013,
    Operator_ID: 20003,
    url: "./img/Product1.png",
    Operator_Name: "Basket of gold",
    Event_Category: "Carnival",
    Event_Name: "Carnival",
    Event_Description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut...",
    Event_Start_Date: "Dec 11, 2022",
    Event_End_Date: "Dec 11, 2022",
    Event_Rank: "three.svg",
    Event_Start_Time: "7:00 PM",
    Event_Counter_Time: 3600 * 5,
    Event_End_Time: "7:30PM",
    Seat_Booking_Availability: 20,
    Event_Location: "Sindalah Island",
    Event_Status: "Completed",
    Event_Capacity: 100,
    Overall_Event_Rating: 4.6,
    Operator_Rating: 3,
    Client_Booked: true,
    vibes_text: "Joyed",
  },
  {
    Event_ID: 10013,
    Operator_ID: 20005,
    url: "./img/Product1.png",
    Operator_Name: "Basket of gold",
    Event_Category: "Jazz Concert",
    Event_Name: "Jazz Concert",
    Event_Description:
      "Most awaited concert featuring a spectacular line-up of Grammy-nominated musicians from across the world coming together to create some fine jazz.",
    Event_Start_Date: "Dec 11, 2022",
    Event_End_Date: "Dec 11, 2022",
    Event_Start_Time: "8:00 PM",
    Event_Counter_Time: 3600 * 6,
    Event_Rank: "four.svg",
    Event_End_Time: "11:59 PM",
    Seat_Booking_Availability: 20,
    Event_Location: "Sindalah Island",
    Event_Status: "Completed",
    Event_Capacity: 300,
    Overall_Event_Rating: 4.6,
    Operator_Rating: 5,
    Client_Booked: true,
    vibes_text: "Overwhelmed",
    imgurl: [
      { img: "Jazz1.jpg" },
      { img: "Jazz2.jpg" },
      { img: "Jazz3.jpg" },
      { img: "Jazz4.jpg" },
      { img: "Jazz5.jpg" },
    ],
  },
  {
    Event_ID: 10003,
    Operator_ID: 20003,
    url: "./img/Product1.png",
    Operator_Name: "Basket of gold",
    Event_Category: "Yacht Party",
    Event_Name: "Yacht Party",
    Event_Description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut...",
    Event_Start_Date: "Dec 11, 2022",
    Event_End_Date: "11/29/2022",
    Event_Start_Time: "8:00 PM",
    Event_Counter_Time: 3600 * 6,
    Event_End_Time: "05:00 PM",
    Event_Rank: "five.svg",
    Seat_Booking_Availability: 20,
    Event_Location: "Sindalah Island",
    Event_Status: "Completed",
    Event_Capacity: 100,
    Overall_Event_Rating: 4.6,
    Operator_Rating: 3,
    Client_Booked: true,
    vibes_text: "Joyed",
    imgurl: [
      { img: "surfing.jpg" },
      { img: "surfing.jpg" },
      { img: "surfing.jpg" },
      { img: "surfing.jpg" },
      { img: "surfing.jpg" },
    ],
  },
];
const EventDetail =
    [
        {
            "Event_ID": 10101,
            "itinerary":true,
            "Operator_ID": 20005,
            "url":'expo.jpg',
            "Operator_Name": "Basket of gold",
            "Event_Category": "Tech Expo",
            "Event_Name": "Tech Expo",
            "Event_Description": "Most awaited concert featuring a spectacular line-up of Grammy-nominated musicians from across the world coming together to create some fine Tech Expo.",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 11, 2022",
            "Event_Start_Time": "3:00 PM",
            "Event_End_Time": "11:59 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Scheduled",
            "Event_Capacity": 300,
            "Overall_Event_Rating": 4.6,
            "Operator_Rating": 5,
            "vibes_text":"Overwhelmed vibes",
            "Event_Detail_Title":"Sunday Night All That Jazz Concert",
            "Event_Detail_Des1":"Every last Sunday of the month, prepare to dive into the fascinating world of jazz, in a journey led by Ed Jackson that will allow you to experience the pleasant sensations of life which is hosted by Jackson Room in Sindalah Island.  An intimate ambience in a beautiful venue where music, dance and song combine to make you feel the emotions of Jazz in its purest form.",
            "Event_Detail_Des2":"Ed Jackson is an accomplished saxophonist & active jazz player on the NY & International scene. Ed Jackson’s dynamic sound encompasses both the tradition and future of jazz. His versatility enables him to move within the various styles of jazz while at the same time maintaining a unique sound and direction.",
            "Event_Detail_Des3":"Jazz music in general hits every chord in our lives, and Ed Jackson knows how to play it. So why not join us and allow your mind to wander, relax, and unwind. Whether you’re looking for a beautifully unique classical music performance or a romantic candlelit experience, this performance is for you. Simply sit back and savour the stunning atmosphere and pieces you’ll hear.",
            "Operator_Title": "Marriot Vacation Club",
            "Operator_Des": "Discover Your World with Marriot's collection of amazing experiences. Whether you are looking for sumo wrestling classes in Tokyo, skip-the-line tickets at the Eiffel Tower, or a custom wine tour in Cape Town, we have options for every traveler.",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"First time in Jazz Alley, the place was filled with various groups of people eating, drinking, and chatting. Our table was in good position, plus I was able to see the stage very well. We ordered some cocktails and everyone looked relaxed and enjoying their evening"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"The “All that Jazz” concert at the Sindalah Island was an enjoyable evening. It was full of good music that stimulated my intellectual and musical experience."},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "Jazz1.jpg"},
                {"img": "Jazz2.jpg"},
                {"img": "Jazz3.jpg"},
                {"img": "Jazz4.jpg"},
                {"img": "Jazz5.jpg"},
            ]
        },
        {
        "Event_ID": 10102,
            "itinerary":true,
        "Operator_ID": 20002,
        "url":'golf.jpg',
        "Operator_Name": "Dark Roast",
        "Event_Category": "Golf",
        "Event_Name": "Round of Golf",
        "Event_Description": "The course will test even the most seasoned golfer due to cunning bunker design and water hazards that affect twelve of the eighteen holes...",
        "Event_Start_Date": "Dec 11, 2022",
        "Event_End_Date": "Dec 11, 2022",
        "Event_Start_Time": "3:00 PM",
        "Event_End_Time": "4:00 PM",
        "Seat_Booking_Availability": 20,
        "Event_Location": "Sindalah Island",
        "Event_Status": "Cancelled",
        "Event_Capacity": 200,
        "Overall_Event_Rating": 4.0,
        "Operator_Rating": 3,
          "vibes_text":"Invigorating & Uplifting",
           "isCancelledPossible":true,

            "Event_Detail_Title":"Tee Off at Sindalah's green master course",
            "Event_Detail_Des1":"The 1st hole at the Sindalah Golf Course  is a straightforward 128 yards opening hole giving ample opportunity to start the round with a birdie. Depending on the placement of the tee markers and the pin location, this hole can play as a short 110 yarder making it an aggressive starter too. Only place to miss this green is short of it, as bunkers line the left side and thick bushes and trees flank the right, with little room for error.",
            "Event_Detail_Des2":"The 2nd, an Iconic 269 yard dog-leg left par 4, is the most challenging hole on the Sindalah Golf Course. Making a par is a bonus on this hole for the average golfer. The safest way to play is to the right of the fairway bunker at 128 yards leaving a 107 yard approach over an imposing date tree nearly 80 feet high. Alternately the trees on the left of an intimidating narrow fairway can be hit over to cut the dogleg to the green 230 yards away, but with dire consequences in case of an errant or especially a pulled shot. Either way a hugely daunting par 4 that allows no room for error. Placement of the tee shot is critical. Expect a bogey or worse if one is even marginally wayward on this hole",
            "Event_Detail_Des3":"",
            "Operator_Title": "IMG Golf Course",
            "Operator_Des": "IMG is a global leader in the design, development, marketing and management of world class golf courses. For more than 30 years, the company has set the standard for excellence in golf course design and golf club management, and consistently delivered exceptional results for our clients and partners.",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
            {"img": "Golf11.png"},
            {"img": "Golf12.png"},
            {"img": "Golf13.png"},
            {"img": "Golf14.png"},
            {"img": "Golf15.png"},
            {"img": "Golf16.png"},
          ]
        },
        {
            "Event_ID": 10103,
            "itinerary":true,
            "Operator_ID": 20002,
            "url":'Dining.jpg',
            "Operator_Name": "Dark Roast",
            "Event_Category": "Dining",
            "Event_Name": "Epicurean Cuisine",
            "Event_Description": "Enjoy new dishes made from weekly air-flown ingredients from Mediterranean Sea...",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 11, 2022",
            "Event_Start_Time": "6:30 PM",
            "Event_End_Time": "9:00 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Scheduled",
            "Event_Capacity": 200,
            "Overall_Event_Rating": 3.0,
            "Operator_Rating": 3,
            "vibes_text":"Vibrant & Social",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "Dinning-1.jpg"},
                {"img": "Dinning-2.jpg"},
                {"img": "Dinning-3.jpg"},
                {"img": "Dinning-4.jpg"},
                {"img": "Dinning-5.jpg"},

            ]
        },

        {
            "Event_ID": 10104,
            "itinerary":true,
            "Operator_ID": 20002,
            "url":'golf.jpg',
            "Operator_Name": "Dark Roast",
            "Event_Category": "Golf",
            "Event_Name": "Round of Golf",
            "Event_Description": "The course will test even the most seasoned golfer due to cunning bunker design and water hazards that affect twelve of the eighteen holes...",
            "Event_Start_Date": "Dec 13, 2022",
            "Event_End_Date": "Dec 13, 2022",
            "Event_Start_Time": "4:30 PM",
            "Event_End_Time": "5:30 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Re-Scheduled",
            "Event_Capacity": 200,
            "Overall_Event_Rating": 4.1,
            "Operator_Rating": 3,
            "vibes_text":"Invigorating & Uplifting",
            "isCancelledPossible":true,
            // "Client_Booked": true,
            "Event_Detail_Title":"Tee Off at Sindalah's green master course",
            "Event_Detail_Des1":"The 1st hole at the Sindalah Golf Course  is a straightforward 128 yards opening hole giving ample opportunity to start the round with a birdie. Depending on the placement of the tee markers and the pin location, this hole can play as a short 110 yarder making it an aggressive starter too. Only place to miss this green is short of it, as bunkers line the left side and thick bushes and trees flank the right, with little room for error.",
            "Event_Detail_Des2":"The 2nd, an Iconic 269 yard dog-leg left par 4, is the most challenging hole on the Sindalah Golf Course. Making a par is a bonus on this hole for the average golfer. The safest way to play is to the right of the fairway bunker at 128 yards leaving a 107 yard approach over an imposing date tree nearly 80 feet high. Alternately the trees on the left of an intimidating narrow fairway can be hit over to cut the dogleg to the green 230 yards away, but with dire consequences in case of an errant or especially a pulled shot. Either way a hugely daunting par 4 that allows no room for error. Placement of the tee shot is critical. Expect a bogey or worse if one is even marginally wayward on this hole",
            "Event_Detail_Des3":"",
            "Operator_Title": "IMG Golf Course",
            "Operator_Des": "IMG is a global leader in the design, development, marketing and management of world class golf courses. For more than 30 years, the company has set the standard for excellence in golf course design and golf club management, and consistently delivered exceptional results for our clients and partners.",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "Golf11.png"},
                {"img": "Golf12.png"},
                {"img": "Golf13.png"},
                {"img": "Golf14.png"},
                {"img": "Golf15.png"},
                {"img": "Golf16.png"},
            ]
        },
        {
            "Event_ID": 10105,
            "itinerary":true,
            "Operator_ID": 20002,
            "url":'Dining.jpg',
            "Operator_Name": "Dark Roast",
            "Event_Category": "Dining",
            "Event_Name": "Epicurean Cuisine",
            "Event_Description": "Enjoy new dishes made from weekly air-flown ingredients from Mediterranean Sea...",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 12, 2022",
            "Event_Start_Time": "6:30 PM",
            "Event_End_Time": "",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Scheduled",
            "Event_Capacity": 200,
            "Overall_Event_Rating": 3.0,
            "Operator_Rating": 3,
            "vibes_text":"Vibrant & Social",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "Dinning-1.jpg"},
                {"img": "Dinning-2.jpg"},
                {"img": "Dinning-3.jpg"},
                {"img": "Dinning-4.jpg"},
                {"img": "Dinning-5.jpg"},

            ]
        },


        {
            "Event_ID": 10106,
            "itinerary":true,
            "Operator_ID": 20002,
            "url":'golf.jpg',
            "Operator_Name": "Dark Roast",
            "Event_Category": "Golf",
            "Event_Name": "Round of Golf",
            "Event_Description": "The course will test even the most seasoned golfer due to cunning bunker design and water hazards that affect twelve of the eighteen holes...",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 12, 2022",
            "Event_Start_Time": "3:00 PM",
            "Event_End_Time": "5:30 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Scheduled",
            "Event_Capacity": 200,
            "Overall_Event_Rating": 4.0,
            "Operator_Rating": 3,
            "vibes_text":"Invigorating & Uplifting",
            "isCancelledPossible":true,
            // "Client_Booked": true,
            "Event_Detail_Title":"Tee Off at Sindalah's green master course",
            "Event_Detail_Des1":"The 1st hole at the Sindalah Golf Course  is a straightforward 128 yards opening hole giving ample opportunity to start the round with a birdie. Depending on the placement of the tee markers and the pin location, this hole can play as a short 110 yarder making it an aggressive starter too. Only place to miss this green is short of it, as bunkers line the left side and thick bushes and trees flank the right, with little room for error.",
            "Event_Detail_Des2":"The 2nd, an Iconic 269 yard dog-leg left par 4, is the most challenging hole on the Sindalah Golf Course. Making a par is a bonus on this hole for the average golfer. The safest way to play is to the right of the fairway bunker at 128 yards leaving a 107 yard approach over an imposing date tree nearly 80 feet high. Alternately the trees on the left of an intimidating narrow fairway can be hit over to cut the dogleg to the green 230 yards away, but with dire consequences in case of an errant or especially a pulled shot. Either way a hugely daunting par 4 that allows no room for error. Placement of the tee shot is critical. Expect a bogey or worse if one is even marginally wayward on this hole",
            "Event_Detail_Des3":"",
            "Operator_Title": "IMG Golf Course",
            "Operator_Des": "IMG is a global leader in the design, development, marketing and management of world class golf courses. For more than 30 years, the company has set the standard for excellence in golf course design and golf club management, and consistently delivered exceptional results for our clients and partners.",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "Golf11.png"},
                {"img": "Golf12.png"},
                {"img": "Golf13.png"},
                {"img": "Golf14.png"},
                {"img": "Golf15.png"},
                {"img": "Golf16.png"},
            ]
        },
        {
            "Event_ID": 10107,
            "itinerary":true,
            "Operator_ID": 20002,
            "url":'Dining.jpg',
            "Operator_Name": "Dark Roast",
            "Event_Category": "Dining",
            "Event_Name": "Epicurean Cuisine",
            "Event_Description": "Enjoy new dishes made from weekly air-flown ingredients from Mediterranean Sea...",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 12, 2022",
            "Event_Start_Time": "6:30 PM",
            "Event_End_Time": "11:00 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Scheduled",
            "Event_Capacity": 200,
            "Overall_Event_Rating": 3.0,
            "Operator_Rating": 3,
            "vibes_text":"Vibrant & Social",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "Dinning-1.jpg"},
                {"img": "Dinning-2.jpg"},
                {"img": "Dinning-3.jpg"},
                {"img": "Dinning-4.jpg"},
                {"img": "Dinning-5.jpg"},

            ]
        },



        {
          "Event_ID": 10005,
          "Operator_ID": 20004,
          "url":'golf.jpg',
          "Operator_Name": "Northern lights",
          "Event_Category": "Golf",
          "Event_Name": "Golf tournament",
          "Event_Description": "The course will test even the most seasoned golfer due to cunning bunker design and water hazards that affect twelve of the eighteen holes",
          "Event_Start_Date": "Dec 11, 2022",
          "Event_End_Date": "Dec 11, 2022",
          "Event_Start_Time": "02:00 PM",
          "Event_End_Time": "05:00 PM",
          "Seat_Booking_Availability": 30,
          "Event_Location": "Sindalah Island",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 250,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 4,
            "Event_Detail_Title":"Tee Off at Sindalah's green master course",
            "Event_Detail_Des1":"The 1st hole at the Sindalah Golf Course  is a straightforward 128 yards opening hole giving ample opportunity to start the round with a birdie. Depending on the placement of the tee markers and the pin location, this hole can play as a short 110 yarder making it an aggressive starter too. Only place to miss this green is short of it, as bunkers line the left side and thick bushes and trees flank the right, with little room for error.",
            "Event_Detail_Des2":"The 2nd, an Iconic 269 yard dog-leg left par 4, is the most challenging hole on the Sindalah Golf Course. Making a par is a bonus on this hole for the average golfer. The safest way to play is to the right of the fairway bunker at 128 yards leaving a 107 yard approach over an imposing date tree nearly 80 feet high. Alternately the trees on the left of an intimidating narrow fairway can be hit over to cut the dogleg to the green 230 yards away, but with dire consequences in case of an errant or especially a pulled shot. Either way a hugely daunting par 4 that allows no room for error. Placement of the tee shot is critical. Expect a bogey or worse if one is even marginally wayward on this hole",
            "Event_Detail_Des3":"",
            "Operator_Title": "IMG Golf Course",
            "Operator_Des": "IMG is a global leader in the design, development, marketing and management of world class golf courses. For more than 30 years, the company has set the standard for excellence in golf course design and golf club management, and consistently delivered exceptional results for our clients and partners.",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
              {"img": "Golf11.png"},
              {"img": "Golf12.png"},
              {"img": "Golf13.png"},
              {"img": "Golf14.png"},
              {"img": "Golf15.png"},
              {"img": "Golf16.png"},
          ]
        },
        {
          "Event_ID": 10006,
          "Operator_ID": 20005,
            "url":'surfing.jpg',
            "Operator_Name": "Basket of gold",
            "Event_Category": "Surfing",
            "Event_Name": "Surfing at leisure",
            "Event_Description": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut...",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 11, 2022",
            "Event_Start_Time": "10:00 PM",
            "Event_End_Time": "05:00 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Not Sarted",
            "Event_Capacity": 300,
            "Overall_Event_Rating": 4.6,
            "Operator_Rating": 5,
            "vibes_text":"Overwhelmed vibes",
            "Event_Detail_Title":"Riding the Waves",
            "Event_Detail_Des1":"The Riding The Waves surfing experience is all about freedom in the waves, good vibes, not taking things too seriously and learning to just go with the flow. Enjoy world-class waves and dive into the Sindalah surf experience with us. We will guide you to the best surf spots around Sindalah. No one knows the Sindalah waves and spots better than our local Surf Instructors. Whether this is your first surf holiday or you’re an advanced surfer,  we respond to you individually and teach you to surf in a fun and efficient way. Professional and experienced surf teachers coach you using unique techniques acquired through years of experience. They speak a number of languages so communication is easy, guaranteeing a successful surf holiday.",
            "Event_Detail_Des2":"",
            "Event_Detail_Des3":"",
            "Operator_Title": "Dive Butler",
            "Operator_Des": "Dive Butler are pioneers in the field of true luxury diving, providing private, personal scuba diving guides and instructors to super yachts, charter companies, luxury 5 Star resorts and individuals across the world. Our global services include, but are not limited to, one-to-one diving instructors, private diving guides, yacht itinerary planning, PADI course certifications and on board dive consultation services.",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "surfing_image.png"},
                {"img": "surfing_image.png"},
                {"img": "surfing_image.png"},
                {"img": "surfing_image.png"},
                {"img": "surfing_image.png"},
            ]
        },
        {
          "Event_ID": 10007,
          "Operator_ID": 20005,
            "url":'yacht.jpg',
            "Operator_Name": "Basket of gold",
            "Event_Category": "Jazz Music",
            "Event_Name": "Jazz Music",
            "Event_Description": "Most awaited concert featuring a spectacular line-up of Grammy-nominated musicians from across the world coming together to create some fine jazz.",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 11, 2022",
            "Event_Start_Time": "10:00 PM",
            "Event_End_Time": "05:00 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Not Sarted",
            "Event_Capacity": 300,
            "Overall_Event_Rating": 4.6,
            "Operator_Rating": 5,
            "vibes_text":"Overwhelmed vibes",
            "Event_Detail_Title":"Sunday Night All That Jazz Concert",
            "Event_Detail_Des1":"Every last Sunday of the month, prepare to dive into the fascinating world of jazz, in a journey led by Ed Jackson that will allow you to experience the pleasant sensations of life which is hosted by Jackson Room in Sindalah Island.  An intimate ambience in a beautiful venue where music, dance and song combine to make you feel the emotions of Jazz in its purest form.",
            "Event_Detail_Des2":"Ed Jackson is an accomplished saxophonist & active jazz player on the NY & International scene. Ed Jackson’s dynamic sound encompasses both the tradition and future of jazz. His versatility enables him to move within the various styles of jazz while at the same time maintaining a unique sound and direction.",
            "Event_Detail_Des3":"Jazz music in general hits every chord in our lives, and Ed Jackson knows how to play it. So why not join us and allow your mind to wander, relax, and unwind. Whether you’re looking for a beautifully unique classical music performance or a romantic candlelit experience, this performance is for you. Simply sit back and savour the stunning atmosphere and pieces you’ll hear.",
            "Operator_Title": "Marriot Vacation Club",
            "Operator_Des": "Discover Your World with Marriot's collection of amazing experiences. Whether you are looking for sumo wrestling classes in Tokyo, skip-the-line tickets at the Eiffel Tower, or a custom wine tour in Cape Town, we have options for every traveler.",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"First time in Jazz Alley, the place was filled with various groups of people eating, drinking, and chatting. Our table was in good position, plus I was able to see the stage very well. We ordered some cocktails and everyone looked relaxed and enjoying their evening"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"The “All that Jazz” concert at the Sindalah Island was an enjoyable evening. It was full of good music that stimulated my intellectual and musical experience."},
            ],
            "imgurl":[
                {"img": "Jazz1.jpg"},
                {"img": "Jazz2.jpg"},
                {"img": "Jazz3.jpg"},
                {"img": "Jazz4.jpg"},
                {"img": "Jazz5.jpg"},
            ]
        },
        {
          "Event_ID": 10008,
          "Operator_ID": 20006,
            "url":'dive.jpg',
            "Operator_Name": "Basket of gold",
            "Event_Category": "Sweet Wonderland",
            "Event_Name": "Sweet Wonderland",
            "Event_Description": "Sweet Wonderland",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 11, 2022",
            "Event_Start_Time": "10:00 PM",
            "Event_End_Time": "05:00 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Not Sarted",
            "Event_Capacity": 300,
            "Overall_Event_Rating": 4.6,
            "Operator_Rating": 5,
            "vibes_text":"Overwhelmed vibes",

            "Event_Detail_Title":"The Wonder Carnival",
            "Event_Detail_Des1":"Strap yourselves in as The Wonder Carnival - a full-fledged fun fiesta here with unlimited merrymaking and revelry, taking place at Sindalah Island. Carnival celebrations are a spectacle, filled with cuisine, entertainment, live music, and colorful, over-the-top costumes. From shimmering feathery headpieces to wooden shoes, it's an event you won't want to miss. For many, it’s a time to let loose and indulge one last time before the start of Lent. For others, it's a way to reflect and celebrate the joy of life. ",
            "Event_Detail_Des2":"You can dance on the streets with the crowd for free and wear whatever you want, but locals tend to wear t-shirts and shorts. If you prefer to watch from the sidelines, you can do so from a camarote (cabin) located along the parade avenues.",
            "Event_Detail_Des3":"Dress code: If you are planning to visit  for Carnival, you should dress up in costume to be a part of the fun. The best part? There are no rules, so you can dress up as anything, like you would for Halloween.",
            "Operator_Title": "Four Seasons",
            "Operator_Des": "Four Seasons Hotels and Resorts is an international luxury hotel and resort company headquartered in Toronto, Ontario, Canada. Four Seasons currently operates more than 100 hotels and resorts worldwide. ",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "dive.jpg"},
                {"img": "dive.jpg"},
                {"img": "dive.jpg"},
                {"img": "dive.jpg"},
                {"img": "dive.jpg"},
            ]
        },
        {
          "Event_ID": 10009,
          "Operator_ID": 20007,
            "url":'beach.jpg',
            "Operator_Name": "Basket of gold",
            "Event_Category": "Surfing",
            "Event_Name": "Kite Surfing",
            "Event_Description": "Kite Surfing",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 11, 2022",
            "Event_Start_Time": "10:00 PM",
            "Event_End_Time": "05:00 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Not Sarted",
            "Event_Capacity": 300,
            "Overall_Event_Rating": 4.6,
            "Operator_Rating": 5,
            "vibes_text":"Overwhelmed vibes",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "kite_surfing.png"},
                {"img": "kite_surfing.png"},
                {"img": "kite_surfing.png"},
                {"img": "kite_surfing.png"},
                {"img": "kite_surfing.png"},
            ]
        },

        {
            "Event_ID": 10010,
            "itinerary":true,
            "Operator_ID": 20004,
            "url":'golf.jpg',
            "Operator_Name": "Northern lights",
            "Event_Category": "Golf",
            "Event_Name": "Golf tournament",
            "Event_Description": "The course will test even the most seasoned golfer due to cunning bunker design and water hazards that affect twelve of the eighteen holes",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 11, 2022",
            "Event_Start_Time": "02:00 PM",
            "Event_End_Time": "05:00 PM",
            "Seat_Booking_Availability": 30,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Completed",
            "Event_Capacity": 250,
            "Overall_Event_Rating": 4.6,
            "Operator_Rating": 4,
            "Client_Booked": true,
            "Event_Detail_Title":"Tee Off at Sindalah's green master course",
            "Event_Detail_Des1":"The 1st hole at the Sindalah Golf Course  is a straightforward 128 yards opening hole giving ample opportunity to start the round with a birdie. Depending on the placement of the tee markers and the pin location, this hole can play as a short 110 yarder making it an aggressive starter too. Only place to miss this green is short of it, as bunkers line the left side and thick bushes and trees flank the right, with little room for error.",
            "Event_Detail_Des2":"The 2nd, an Iconic 269 yard dog-leg left par 4, is the most challenging hole on the Sindalah Golf Course. Making a par is a bonus on this hole for the average golfer. The safest way to play is to the right of the fairway bunker at 128 yards leaving a 107 yard approach over an imposing date tree nearly 80 feet high. Alternately the trees on the left of an intimidating narrow fairway can be hit over to cut the dogleg to the green 230 yards away, but with dire consequences in case of an errant or especially a pulled shot. Either way a hugely daunting par 4 that allows no room for error. Placement of the tee shot is critical. Expect a bogey or worse if one is even marginally wayward on this hole",
            "Event_Detail_Des3":"",
            "Operator_Title": "IMG Golf Course",
            "Operator_Des": "IMG is a global leader in the design, development, marketing and management of world class golf courses. For more than 30 years, the company has set the standard for excellence in golf course design and golf club management, and consistently delivered exceptional results for our clients and partners.",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "Golf11.png"},
                {"img": "Golf12.png"},
                {"img": "Golf13.png"},
                {"img": "Golf14.png"},
                {"img": "Golf15.png"},
                {"img": "Golf16.png"},
            ]
        },
        {
            "Event_ID": 10011,
            "itinerary":true,
            "Operator_ID": 20005,
            "url":'surfing.jpg',
            "Operator_Name": "Basket of gold",
            "Event_Category": "Surfing",
            "Event_Name": "Surfing at leisure",
            "Event_Description": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut...",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 11, 2022",
            "Event_Start_Time": "10:00 PM",
            "Event_End_Time": "05:00 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Completed",
            "Event_Capacity": 300,
            "Overall_Event_Rating": 4.6,
            "Operator_Rating": 5,
            "Client_Booked": true,
            "vibes_text":"Overwhelmed vibes",

            "Event_Detail_Title":"Riding the Waves",
            "Event_Detail_Des1":"The Riding The Waves surfing experience is all about freedom in the waves, good vibes, not taking things too seriously and learning to just go with the flow. Enjoy world-class waves and dive into the Sindalah surf experience with us. We will guide you to the best surf spots around Sindalah. No one knows the Sindalah waves and spots better than our local Surf Instructors. Whether this is your first surf holiday or you’re an advanced surfer,  we respond to you individually and teach you to surf in a fun and efficient way. Professional and experienced surf teachers coach you using unique techniques acquired through years of experience. They speak a number of languages so communication is easy, guaranteeing a successful surf holiday.",
            "Event_Detail_Des2":"",
            "Event_Detail_Des3":"",
            "Operator_Title": "Dive Butler",
            "Operator_Des": "Dive Butler are pioneers in the field of true luxury diving, providing private, personal scuba diving guides and instructors to super yachts, charter companies, luxury 5 Star resorts and individuals across the world. Our global services include, but are not limited to, one-to-one diving instructors, private diving guides, yacht itinerary planning, PADI course certifications and on board dive consultation services.",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "surfing_image.png"},
                {"img": "surfing_image.png"},
                {"img": "surfing_image.png"},
                {"img": "surfing_image.png"},
                {"img": "surfing_image.png"},
            ]
        },
        {
            "Event_ID": 10012,
            "itinerary":true,
            "Operator_ID": 20005,
            "url":'yacht.jpg',
            "Operator_Name": "Basket of gold",
            "Event_Category": "Jazz Music",
            "Event_Name": "Jazz Music",
            "Event_Description": "Most awaited concert featuring a spectacular line-up of Grammy-nominated musicians from across the world coming together to create some fine jazz.",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 11, 2022",
            "Event_Start_Time": "10:00 PM",
            "Event_End_Time": "05:00 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Completed",
            "Event_Capacity": 300,
            "Overall_Event_Rating": 4.6,
            "Operator_Rating": 5,
            "Client_Booked": true,
            "vibes_text":"Overwhelmed vibes",
            "Event_Detail_Title":"Sunday Night All That Jazz Concert",
            "Event_Detail_Des1":"Every last Sunday of the month, prepare to dive into the fascinating world of jazz, in a journey led by Ed Jackson that will allow you to experience the pleasant sensations of life which is hosted by Jackson Room in Sindalah Island.  An intimate ambience in a beautiful venue where music, dance and song combine to make you feel the emotions of Jazz in its purest form.",
            "Event_Detail_Des2":"Ed Jackson is an accomplished saxophonist & active jazz player on the NY & International scene. Ed Jackson’s dynamic sound encompasses both the tradition and future of jazz. His versatility enables him to move within the various styles of jazz while at the same time maintaining a unique sound and direction.",
            "Event_Detail_Des3":"Jazz music in general hits every chord in our lives, and Ed Jackson knows how to play it. So why not join us and allow your mind to wander, relax, and unwind. Whether you’re looking for a beautifully unique classical music performance or a romantic candlelit experience, this performance is for you. Simply sit back and savour the stunning atmosphere and pieces you’ll hear.",
            "Operator_Title": "Marriot Vacation Club",
            "Operator_Des": "Discover Your World with Marriot's collection of amazing experiences. Whether you are looking for sumo wrestling classes in Tokyo, skip-the-line tickets at the Eiffel Tower, or a custom wine tour in Cape Town, we have options for every traveler.",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"First time in Jazz Alley, the place was filled with various groups of people eating, drinking, and chatting. Our table was in good position, plus I was able to see the stage very well. We ordered some cocktails and everyone looked relaxed and enjoying their evening"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"The “All that Jazz” concert at the Sindalah Island was an enjoyable evening. It was full of good music that stimulated my intellectual and musical experience."},
            ],
            "imgurl":[
                {"img": "Jazz1.jpg"},
                {"img": "Jazz2.jpg"},
                {"img": "Jazz3.jpg"},
                {"img": "Jazz4.jpg"},
                {"img": "Jazz5.jpg"},
            ]
        },
        {
            "Event_ID": 10013,
            "itinerary":true,
            "Operator_ID": 20006,
            "url":'dive.jpg',
            "Operator_Name": "Basket of gold",
            "Event_Category": "Sweet Wonderland",
            "Event_Name": "Sweet Wonderland",
            "Event_Description": "Sweet Wonderland",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 11, 2022",
            "Event_Start_Time": "10:00 PM",
            "Event_End_Time": "05:00 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Completed",
            "Event_Capacity": 300,
            "Overall_Event_Rating": 4.6,
            "Operator_Rating": 5,
            "Client_Booked": true,
            "vibes_text":"Overwhelmed vibes",
            "Event_Detail_Title":"The Wonder Carnival",
            "Event_Detail_Des1":"Strap yourselves in as The Wonder Carnival - a full-fledged fun fiesta here with unlimited merrymaking and revelry, taking place at Sindalah Island. Carnival celebrations are a spectacle, filled with cuisine, entertainment, live music, and colorful, over-the-top costumes. From shimmering feathery headpieces to wooden shoes, it's an event you won't want to miss. For many, it’s a time to let loose and indulge one last time before the start of Lent. For others, it's a way to reflect and celebrate the joy of life. ",
            "Event_Detail_Des2":"You can dance on the streets with the crowd for free and wear whatever you want, but locals tend to wear t-shirts and shorts. If you prefer to watch from the sidelines, you can do so from a camarote (cabin) located along the parade avenues.",
            "Event_Detail_Des3":"Dress code: If you are planning to visit  for Carnival, you should dress up in costume to be a part of the fun. The best part? There are no rules, so you can dress up as anything, like you would for Halloween.",
            "Operator_Title": "Four Seasons",
            "Operator_Des": "Four Seasons Hotels and Resorts is an international luxury hotel and resort company headquartered in Toronto, Ontario, Canada. Four Seasons currently operates more than 100 hotels and resorts worldwide. ",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "dive.jpg"},
                {"img": "dive.jpg"},
                {"img": "dive.jpg"},
                {"img": "dive.jpg"},
                {"img": "dive.jpg"},
            ]
        },
        {
            "Event_ID": 10014,
            "itinerary":true,
            "Operator_ID": 20007,
            "url":'beach.jpg',
            "Operator_Name": "Basket of gold",
            "Event_Category": "Surfing",
            "Event_Name": "Kite Surfing",
            "Event_Description": "Kite Surfing",
            "Event_Start_Date": "Dec 11, 2022",
            "Event_End_Date": "Dec 11, 2022",
            "Event_Start_Time": "10:00 PM",
            "Event_End_Time": "05:00 PM",
            "Seat_Booking_Availability": 20,
            "Event_Location": "Sindalah Island",
            "Event_Status": "Completed",
            "Event_Capacity": 300,
            "Overall_Event_Rating": 4.6,
            "Operator_Rating": 5,
            "Client_Booked": true,
            "vibes_text":"Overwhelmed vibes",
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
            "imgurl":[
                {"img": "kite_surfing.png"},
                {"img": "kite_surfing.png"},
                {"img": "kite_surfing.png"},
                {"img": "kite_surfing.png"},
                {"img": "kite_surfing.png"},
            ]
        },

        {
          "Event_ID": 100015,
          "Operator_ID": 20008,
          "Operator_Name": "Painted Desert",
          "Event_Category": "Exhibitions ",
          "Event_Name": "Book Exhibitions",
          "Event_Description": "Historical Book Exhibitions",
          "Event_Start_Date": "Dec 11, 2022",
          "Event_End_Date": "Dec 11, 2022",
          "Event_Start_Time": "05:00 PM",
          "Event_End_Time": "10:30 PM",
          "Seat_Booking_Availability": 15,
          "Event_Location": "Sindalah Island",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 200,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 3,
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
        },
        {
          "Event_ID": 100016,
          "Operator_ID": 20009,
          "Operator_Name": "Blue Events",
          "Event_Category": "Music ",
          "Event_Name": "Jazz Concert",
          "Event_Description": "Steam Down",
          "Event_Start_Date": "Dec 11, 2022",
          "Event_End_Date": "Dec 11, 2022",
          "Event_Start_Time": "05:00 PM",
          "Event_End_Time": "10:30 PM",
          "Seat_Booking_Availability": 20,
          "Event_Location": "Sindalah Island",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 100,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 3,
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
        },
        {
          "Event_ID": 100017,
          "Operator_ID": 20009,
          "Operator_Name": "Blue Events",
          "Event_Category": "Music ",
          "Event_Name": "Rock Concert",
          "Event_Description": "Rolling Stone",
          "Event_Start_Date": "Dec 11, 2022",
          "Event_End_Date": "Dec 11, 2022",
          "Event_Start_Time": "05:00 PM",
          "Event_End_Time": "10:30 PM",
          "Seat_Booking_Availability": 5,
          "Event_Location": "Sindalah Island",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 50,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 3,
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
        },
        {
          "Event_ID": 100018,
          "Operator_ID": 20009,
          "Operator_Name": "Blue Events",
          "Event_Category": "Music ",
          "Event_Name": "Piano Classes",
          "Event_Description": "Piano basics",
          "Event_Start_Date": "Dec 11, 2022",
          "Event_End_Date": "Dec 11, 2022",
          "Event_Start_Time": "05:00 PM",
          "Event_End_Time": "10:30 PM",
          "Seat_Booking_Availability": 5,
          "Event_Location": "Sindalah Island",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 20,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 3,
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
        },
        {
          "Event_ID": 100019,
          "Operator_ID": 20003,
          "Operator_Name": "Basket of gold",
          "Event_Category": "carnival",
          "Event_Name": "Sweet Wonderlaw",
          "Event_Description": "Weekly carnival",
          "Event_Start_Date": "Dec 11, 2022",
          "Event_End_Date": "Dec 11, 2022",
          "Event_Start_Time": "05:00 PM",
          "Event_End_Time": "10:30 PM",
          "Seat_Booking_Availability": 5,
          "Event_Location": "Sindalah Island",
          "Event_Status": "Not Sarted",
          "Event_Capacity": 20,
          "Overall_Event_Rating": 4.6,
          "Operator_Rating": 3,
            "RatingSliderCard": [
                {Event_ID:10001,img:"user1.png", rank:"one.svg", city:"Sindalah Island", game:"Golf",  rating:4.0, date:"Nov 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10002,img:"user2.png", rank:"two.svg", city:"Sindalah Island", game:"Golf",  rating:4.9, date:"Oct 2022", title:"Warren", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10003,img:"user3.png", rank:"three.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Oct 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10004,img:"user4.png", rank:"four.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Sep 2022", title:"Martin", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                {Event_ID:10005,img:"user5.png", rank:"five.svg", city:"Sindalah Island", game:"Golf",  rating:3.0, date:"Aug 2022", title:"Anastasia", desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat…"},
                /*{img:"", rank:"", rating:"", date:"", title:"", desc:""},*/
            ],
        }
      ]

const Profile = [
    {
        "Booking_ID":10001,
        "Customer_ID":'001',
        "Customer_Name":"Charlie",
        "Customer_Image":"filepath",
        "Contact_Number":8899112233,
        "Contact_Email":"Charlie@gmail.com",
        "Password":"$abc@",
        "Master_Journey":"Guests",
        "Age":48,
        "dop":'08/01/1979',
        "Gender":"Male",
        "Arrival_Date":"11/25/2022",
        "Arrival_Time":"12:06 PM",
        "Departure_Date":"11/28/2022",
        "Departure_Time":"1:06 PM",
        "Likes":"Golf, Rooms",
        "Dislikes":"Walking for Long",
        "Other/Preferences":"NA",


    },
    {
        "Booking_ID":10001,
        "Customer_ID":'002',
        "Customer_Name":"Shane Mathew",
        "Customer_Image":"filepath",
        "Contact_Number":8699114455,
        "Contact_Email":"syed.kashif@techmahindra.com",
        "Password":"$abc@",
        "Master_Journey":"Guests",
        "Age":50,
        "Gender":"male",
        "Arrival_Date":"11/25/2022",
        "Arrival_Time":"12:06 PM",
        "Departure_Date":"11/28/2022",
        "Departure_Time":"1:06 PM",
        "Likes":"Music, Exploring",
        "Dislikes":"Walking for Long",
        "Other/Preferences":"NA",


    },

    {
        "Booking_ID":10001,
        "Customer_ID":'003',
        "Customer_Name":"Rose Mathey",
        "Customer_Image":"filepath",
        "Contact_Number":9877665544,
        "Contact_Email":"syed.kashif@techmahindra.com",
        "Password":"$abc@",
        "Master_Journey":"Guests",
        "Age":48,
        "Gender":"female",
        "Arrival_Date":"11/25/2022",
        "Arrival_Time":"12:06 PM",
        "Departure_Date":"11/28/2022",
        "Departure_Time":"1:06 PM",
        "Likes":"Cooking",
        "Dislikes":"Chinese food",
        "Other/Preferences":"NA",
    },
    {
        "Booking_ID":10001,
        "Customer_ID":'004',
        "Customer_Name":"Raj Kumar",
        "Customer_Image":"filepath",
        "Contact_Number":6698432271,
        "Contact_Email":"c.sureshkumar@techmahindra.com",
        "Password":"$abc@",
        "Master_Journey":"Guests",
        "Age":13,
        "Gender":"Male",
        "Arrival_Date":"11/19/2022",
        "Arrival_Time":"11:41  PM",
        "Departure_Date":"11/23/2022",
        "Departure_Time":"8:21 AM",
        "Likes":"Comedy Show,Cooking",
        "Dislikes":"Screaming Children",
        "Other/Preferences":"Football",
    }

]

const charliData = [
  {
    img: "./img/Event-Banner.png",
    title: "Indulge in the Finest Epicurean Cuisines",
    detail:
      "Hi Charlie, we came to know from our chef John that you didn't enjoy the Epicurean cuisines yesterday. As a compensation we would like to offer you a free Italian cuisine as a goodwill gesture. Would you like to accept our request?",
    date: "Nov 10-29",
    status: "Yes, I accept",
    notice: "No, thanks",
  },
  {
    img: "./img/holiday_0.png",
    title: "Indulge in the Finest Epicurean Cuisines",
    detail:
      "Hi Charlie, we came to from our chef John that you didn't enjoy the Epicurean cuisines yesterday. As a compensation we would like to offer you a free Italian cuisine as a goodwill gesture. Would you like to accept our request?",
    date: "Nov 10-29",
    status: "Yes, I accept",
    notice: "No, thanks",
  },
  {
    img: "./img/cusine_0.png",
    title: "Indulge in the Finest Epicurean Cuisines",
    detail:
      "Hi Charlie, we came to from our chef John that you didn't enjoy the Epicurean cuisines yesterday. As a compensation we would like to offer you a free Italian cuisine as a goodwill gesture. Would you like to accept our request?",
    date: "Nov 10-29",
    status: "Yes, I accept",
    notice: "No, thanks",
  },
  {
    img: "./img/rolce.png",
    title: "Indulge in the Finest Epicurean Cuisines",
    detail:
      "Hi Charlie, we came to from our chef John that you didn't enjoy the Epicurean cuisines yesterday. As a compensation we would like to offer you a free Italian cuisine as a goodwill gesture. Would you like to accept our request?",
    date: "Nov 10-29",
    status: "Yes, I accept",
    notice: "No, thanks",
  },
];


export {RecommendationData, Treading, Profile, eventDetailImage, EventDetail, RecommendationBannerData, SliderCardData, charliData};
